version: "3.3"

services:
  coder:
    image: docker.io/codercom/coder:1.32.0
    container_name: coder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_FOLDER_PATH}:/var/run/coder
    tty: true
    stdin_open: true
    environment:
      - DEVURL_HOST=${CODER_DOMAIN}
    networks:
      - traefik-public
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
      mode: replicated
      replicas: 1
      placement:
        constraints: ${NODE_PLACEMENT}
      labels:
        traefik.enable: "true"
        traefik.http.routers.coder.rule: Host(`${CODER_DOMAIN}`)
        traefik.http.routers.coder.entrypoints: websecure
        traefik.http.services.coder.loadbalancer.server.port: 7080
        traefik.http.routers.coder.tls.certresolver: letsencrypt


networks:
  traefik-public:
    external: true